### ISSUE TITLE
UI Nomination Count Stops with Draft, End Point Count Continues

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#960] opened 2017-11-28 16:17 UTC
I am still having nomination counts that are off. Nominate a post with two different users. Then send it to draft. Then nominate it with a third person. The nomination count on the UI will say two, but the end point will have all three.  It appears that the UI stops counting nomination once an item is at the draft (post) level.

**Comment by AramZS** [comment] 2017-11-28 16:20
@jccatalano @regan008 Let's talk about this today. I am honestly not sure if we did this intentionally or not. I think we talked about the idea of freezing nominations once an item is sent to draft, I don't think that is what is occurring here, but we need to decide which version of the functionality we should adjust towards.

**Comment by AramZS** [comment] 2017-11-28 16:49
Task: Nomination Count should be incremented in both post and nomination post types when both are available.

**Comment by regan008** [comment] 2017-12-04 16:04
This is still occurring.

**Comment by regan008** [comment] 2017-12-04 16:06
The endpoint now matches the ui's count of nominations however neither are counting the third nomination that occurs after a post has been drafted.

**Comment by AramZS** [comment] 2017-12-04 16:11
Wait... so, on a single feed item: 
 - user 1 - item -> draft occurs (nomination increases everywhere)
 - user 2 - an item -> nomination occurs (nomination increases everywhere)
 - user 3 - an item -> nomination occurs (nominations don't increase anywhere)

Is that right?

**Comment by regan008** [comment] 2017-12-04 16:13
Close its like this: 

- User 1 - nomination occurs (nomination increases everywhere)
- User 2 - nomination occurs (nomination increases everywhere)
- User 2 - drafts content from Nominations
- User 3 - nomination occurs (nominations don't increase anywhere)

**Comment by regan008** [comment] 2017-12-04 18:26
So I'll go ahead and close this but now the issue is that the counts are wrong because it stops counting nominations once a post has been drafted. I will create a new issue for this to clear up any confusions.

**Comment by AramZS** [comment] 2017-12-04 18:27
Awesome, thank you @regan008 that would be hugely useful.

**Closed** 2017-12-04 18:27 UTC
Labels: bug
