### ISSUE TITLE
Confirm that Subscribing to a Feed from the Nominate This bookmarklet works.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#627] opened 2015-07-20 15:44 UTC
Branch: 3.6.x
Component: Nominate This Bookmarklet
Task: Checking off Subscribe to feed when nominating an item.
Expected result: That site's URL or RSS Feed URL will be added to the Subscribed Feeds list.

**Comment by regan008** [comment] 2015-07-20 15:58
@AramZS I'm getting this error when I pull down the 3.6 branch. Looks like there is a missing closing quote in functions.php?

Parse error: syntax error, unexpected '=', expecting ')' in /websites/pftesting/www/wp-content/plugins/pressforward/includes/functions.php on line 1281

**Comment by AramZS** [comment] 2015-07-20 15:59
@regan008 stand by, checking now.

**Comment by AramZS** [comment] 2015-07-20 16:05
@regan008 This seems to be a PHP version issue, what version of PHP are you running? I will alter to make this more backwards compatible.

**Comment by regan008** [comment] 2015-07-20 16:07
@AramZS  I'm not sure, how would I check that?

**Comment by AramZS** [comment] 2015-07-20 16:09
@regan008 do:
```
var_dump(phpversion());
die();
```
on the top of the functions.php file and refresh the WP site. That number is the version. Just delete the line when you're done. 

from: http://php.net/manual/en/function.phpversion.php

**Comment by AramZS** [comment] 2015-07-20 16:13
@regan008 It would be very useful to get that data, but either way, I have pushed up a fix that should resolve this issue and make the branch ready for testing on older versions.

**Comment by regan008** [comment] 2015-07-20 16:13
@AramZS Perfect, here is what I got: string(6) "5.4.33"

**Comment by regan008** [comment] 2015-07-20 16:19
@AramZS Now I get a new error when I pull the most recent 3.6.x branch. It says: `Fatal error: Can't use method return value in write context in /websites/pftesting/www/wp-content/plugins/pressforward/includes/functions.php on line 1281`

**Comment by AramZS** [comment] 2015-07-20 16:25
@regan008 more back-compatibility issues between PHP5.5 vs previous. Fixing.

**Comment by AramZS** [comment] 2015-07-20 16:47
@regan008 Fix pushed up, give it a try.

**Comment by regan008** [comment] 2015-07-20 17:05
@AramZS I haven't been able to get the bookmarklet to subscribe to a feed yet. Is there a way to tell if it is trying and just failing to find the feed url? Should I expect a delay?  It might be useful to have the bookmarklet generate a success or failure message.

**Comment by AramZS** [comment] 2015-07-20 17:07
@regan008 Ummm, can you check the other areas of the Subscribed Feeds area? It may be in the inactive section if it fails.

**Comment by regan008** [comment] 2015-07-20 17:12
@AramZS Hmm yeah I'm not seeing it get added. Let me keep testing -- maybe its the feeds I'm using

**Comment by regan008** [comment] 2015-07-20 17:19
@AramZS So it is adding to subscribed feeds but it appears to be adding the site url not the feed url. Is this expected behavior? 
The url for the feed on this site is: http://diggingdh.com/feed/ but here is what is pulled in: 
![screen shot 2015-07-20 at 1 17 12 pm](https://cloud.githubusercontent.com/assets/4553057/8782182/cb608084-2ee1-11e5-8887-3268b06c6839.png)

**Comment by AramZS** [comment] 2015-07-20 17:46
@regan008 Yes, that should still work fine, our method for RSS reading should understand the feed is an RSS-type and seek the appropriate HEAD tags to find the feed and read it without a problem. That shouldn't cause the feed to fail on its own, but if the site doesn't have the appropriate tags in the HEAD it *will* fail (perhaps causing the issue you saw previously?), and there's no way to solve that in the Nominate This bookmarklet either.

**Comment by regan008** [comment] 2015-07-20 17:48
@AramZS It looks like it hasn't attempted to check the feeds yet. I'll check back in a bit and see if worked. For now though, I'd say this works.

**Comment by regan008** [comment] 2015-07-20 20:13
@AramZS This seems to be working. It is finding and checking feeds nominated through the bookmarklet.

**Closed by regan008** 2015-07-20 20:13 UTC
Labels: Test
